files:
  accept:
  - "**.yar"
  - "**.yara"
false_positives:
  ignore:
   - file: "rules/generic/LNK_Ruleset.yar"
   - file: "rules/generic/AutoIT.yar"
   - file: "rules/generic/Specialist_Repack_Doc.yar"
false_negatives:
  disabled: true
